name: Build and Push Docker Image to AWS ECR
 
on:
  push:
    branches:
      - main  # Trigger action on push to the main branch
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
 
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        region: ${{ secrets.AWS_REGION }}
 
    - name: Extract repository URI
      id: ecr
      run: echo "::set-output name=ecr_uri::$(aws ecr describe-repositories --repository-names ${{ secrets.AWS_ECR_REPOSITORY }} --region ${{ secrets.AWS_REGION }} --query 'repositories[0].repositoryUri' --output text)"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Build and Tag Docker Image
      run: docker build -t ${{ steps.ecr.outputs.ecr_uri }}:latest .
    - name: Push Docker Image to ECR
      run: docker push ${{ steps.ecr.outputs.ecr_uri }}:latest

has context menu
