name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: ${{ secrets.AWS_ECR_REGISTRY }}  # Use the registry URL instead

    - name: Extract repository URI
      id: ecr
      run: echo "::set-output name=ecr_uri::$(aws ecr describe-repositories --repository-names ${{ secrets.AWS_ECR_REPOSITORY }} --query 'repositories[0].repositoryUri' --output text)"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}  # Set region in the environment variables

    - name: Build and Tag Docker Image
      run: docker build -t ${{ steps.ecr.outputs.ecr_uri }}:latest .

    - name: Push Docker Image to ECR
      run: docker push ${{ steps.ecr.outputs.ecr_uri }}:latest
